graphdb:  
  server:
    url:  http://localhost:8080/rdf4j-server
    sparql:
      endpoint:
        url:  http://localhost:7200/sparql
glide:
  eim:
    repository:
      identifier: EnterpriseInformationModel
      name: Enterprise Information Model
    #IRI-defaults: - moved to service call  
      #baseIRI:  http://spec.myenterprisebank.net
      #IRI=type: slash
server:
  port: 16008
  context-path: /eim
    