glide:
  eim:
    graphdb:  
      repository: EnterpriseInformationModel
      server:
        url:  http://localhost:8080/rdf4j-server
      sparql:
          endpoint:
            url:  http://localhost:7200/sparql
    baseOrganizationUri:  "http://spec.mycompany.net/ESS#"
server:
  port: 16008
  context-path: /eim
