graphdb:  
  server:
    url:  http://localhost:8080/rdf4j-server
    sparql:
      endpoint:
        url:  http://localhost:7200/sparql
glide:
  eim:
    repository:
      repo-id: EIM
      repo-name: Enterprise Information Model
      eim-config-graph-context:  eim-config-v1  
server:
  port: 16008
  context-path: /eim
    