
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX fibo-fnd-aap-agt:<http://www.omg.org/spec/EDMC-FIBO/FND/AgentsAndPeople/Agents/>
PREFIX fibo-be-le-fbo:<http://www.omg.org/spec/EDMC-FIBO/BE/LegalEntities/FormalBusinessOrganizations/>
PREFIX my-org:<http://spec.mycompany.net#>
PREFIX eim:<http://spec.trigyan.net/glide/EnterpriseInformationModel#>
SELECT ?orgType ?orgUnit ?orgName ?app ?subunit
	WHERE { ?orgType rdfs:subClassOf fibo-be-le-fbo:OrganizationalSubUnit . 
		?orgUnit rdf:type ?orgType .
		OPTIONAL {?orgUnit fibo-fnd-aap-agt:hasName ?orgName . }
		?orgUnit fibo-be-le-fbo:isSubUnitOf ?subunit .
		OPTIONAL {?app eim:is_owned_by ?orgUnit .}
		
}